name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.6.1
    - name: Set up Poetry env
      run: poetry env use python3.10
    - name: Set up AlphAI dependencies
      run: |
        poetry install --extras "torch docs"
    - name: Deploy docs
      run: poetry run mkdocs gh-deploy --force
